// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/poker/protocols/texaspoker/proto/TexasGameStart.proto

package com.poker.protocols.texaspoker;

public final class TexasGameStartProto {
  private TexasGameStartProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TexasGameStartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.TexasGameStart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *按钮位桌位id
     * </pre>
     *
     * <code>int32 btn_seatId = 1;</code>
     */
    int getBtnSeatId();

    /**
     * <pre>
     *小盲桌位id
     * </pre>
     *
     * <code>int32 sb_seatId = 2;</code>
     */
    int getSbSeatId();

    /**
     * <pre>
     *大盲桌位id
     * </pre>
     *
     * <code>int32 bb_seatId = 3;</code>
     */
    int getBbSeatId();

    /**
     * <pre>
     *ante总数
     * </pre>
     *
     * <code>int64 ante_all = 4;</code>
     */
    long getAnteAll();

    /**
     * <pre>
     *小盲
     * </pre>
     *
     * <code>int64 sb_force_bet_chip = 5;</code>
     */
    long getSbForceBetChip();

    /**
     * <pre>
     *大盲
     * </pre>
     *
     * <code>int64 bb_force_bet_chip = 6;</code>
     */
    long getBbForceBetChip();

    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    java.util.List<com.poker.protocols.texaspoker.GameUserProto.GameUser> 
        getUserList();
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    com.poker.protocols.texaspoker.GameUserProto.GameUser getUser(int index);
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    int getUserCount();
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    java.util.List<? extends com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder> 
        getUserOrBuilderList();
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder getUserOrBuilder(
        int index);
  }
  /**
   * <pre>
   *游戏开始
   * </pre>
   *
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameStart}
   */
  public  static final class TexasGameStart extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.TexasGameStart)
      TexasGameStartOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TexasGameStart.newBuilder() to construct.
    private TexasGameStart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TexasGameStart() {
      btnSeatId_ = 0;
      sbSeatId_ = 0;
      bbSeatId_ = 0;
      anteAll_ = 0L;
      sbForceBetChip_ = 0L;
      bbForceBetChip_ = 0L;
      user_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TexasGameStart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              btnSeatId_ = input.readInt32();
              break;
            }
            case 16: {

              sbSeatId_ = input.readInt32();
              break;
            }
            case 24: {

              bbSeatId_ = input.readInt32();
              break;
            }
            case 32: {

              anteAll_ = input.readInt64();
              break;
            }
            case 40: {

              sbForceBetChip_ = input.readInt64();
              break;
            }
            case 48: {

              bbForceBetChip_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                user_ = new java.util.ArrayList<com.poker.protocols.texaspoker.GameUserProto.GameUser>();
                mutable_bitField0_ |= 0x00000040;
              }
              user_.add(
                  input.readMessage(com.poker.protocols.texaspoker.GameUserProto.GameUser.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          user_ = java.util.Collections.unmodifiableList(user_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameStartProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameStartProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.class, com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.Builder.class);
    }

    private int bitField0_;
    public static final int BTN_SEATID_FIELD_NUMBER = 1;
    private int btnSeatId_;
    /**
     * <pre>
     *按钮位桌位id
     * </pre>
     *
     * <code>int32 btn_seatId = 1;</code>
     */
    public int getBtnSeatId() {
      return btnSeatId_;
    }

    public static final int SB_SEATID_FIELD_NUMBER = 2;
    private int sbSeatId_;
    /**
     * <pre>
     *小盲桌位id
     * </pre>
     *
     * <code>int32 sb_seatId = 2;</code>
     */
    public int getSbSeatId() {
      return sbSeatId_;
    }

    public static final int BB_SEATID_FIELD_NUMBER = 3;
    private int bbSeatId_;
    /**
     * <pre>
     *大盲桌位id
     * </pre>
     *
     * <code>int32 bb_seatId = 3;</code>
     */
    public int getBbSeatId() {
      return bbSeatId_;
    }

    public static final int ANTE_ALL_FIELD_NUMBER = 4;
    private long anteAll_;
    /**
     * <pre>
     *ante总数
     * </pre>
     *
     * <code>int64 ante_all = 4;</code>
     */
    public long getAnteAll() {
      return anteAll_;
    }

    public static final int SB_FORCE_BET_CHIP_FIELD_NUMBER = 5;
    private long sbForceBetChip_;
    /**
     * <pre>
     *小盲
     * </pre>
     *
     * <code>int64 sb_force_bet_chip = 5;</code>
     */
    public long getSbForceBetChip() {
      return sbForceBetChip_;
    }

    public static final int BB_FORCE_BET_CHIP_FIELD_NUMBER = 6;
    private long bbForceBetChip_;
    /**
     * <pre>
     *大盲
     * </pre>
     *
     * <code>int64 bb_force_bet_chip = 6;</code>
     */
    public long getBbForceBetChip() {
      return bbForceBetChip_;
    }

    public static final int USER_FIELD_NUMBER = 7;
    private java.util.List<com.poker.protocols.texaspoker.GameUserProto.GameUser> user_;
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    public java.util.List<com.poker.protocols.texaspoker.GameUserProto.GameUser> getUserList() {
      return user_;
    }
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    public java.util.List<? extends com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    public int getUserCount() {
      return user_.size();
    }
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    public com.poker.protocols.texaspoker.GameUserProto.GameUser getUser(int index) {
      return user_.get(index);
    }
    /**
     * <pre>
     *桌子上用户信息   
     * </pre>
     *
     * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
     */
    public com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (btnSeatId_ != 0) {
        output.writeInt32(1, btnSeatId_);
      }
      if (sbSeatId_ != 0) {
        output.writeInt32(2, sbSeatId_);
      }
      if (bbSeatId_ != 0) {
        output.writeInt32(3, bbSeatId_);
      }
      if (anteAll_ != 0L) {
        output.writeInt64(4, anteAll_);
      }
      if (sbForceBetChip_ != 0L) {
        output.writeInt64(5, sbForceBetChip_);
      }
      if (bbForceBetChip_ != 0L) {
        output.writeInt64(6, bbForceBetChip_);
      }
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(7, user_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (btnSeatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, btnSeatId_);
      }
      if (sbSeatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sbSeatId_);
      }
      if (bbSeatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, bbSeatId_);
      }
      if (anteAll_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, anteAll_);
      }
      if (sbForceBetChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sbForceBetChip_);
      }
      if (bbForceBetChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, bbForceBetChip_);
      }
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, user_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart other = (com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart) obj;

      boolean result = true;
      result = result && (getBtnSeatId()
          == other.getBtnSeatId());
      result = result && (getSbSeatId()
          == other.getSbSeatId());
      result = result && (getBbSeatId()
          == other.getBbSeatId());
      result = result && (getAnteAll()
          == other.getAnteAll());
      result = result && (getSbForceBetChip()
          == other.getSbForceBetChip());
      result = result && (getBbForceBetChip()
          == other.getBbForceBetChip());
      result = result && getUserList()
          .equals(other.getUserList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BTN_SEATID_FIELD_NUMBER;
      hash = (53 * hash) + getBtnSeatId();
      hash = (37 * hash) + SB_SEATID_FIELD_NUMBER;
      hash = (53 * hash) + getSbSeatId();
      hash = (37 * hash) + BB_SEATID_FIELD_NUMBER;
      hash = (53 * hash) + getBbSeatId();
      hash = (37 * hash) + ANTE_ALL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAnteAll());
      hash = (37 * hash) + SB_FORCE_BET_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSbForceBetChip());
      hash = (37 * hash) + BB_FORCE_BET_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBbForceBetChip());
      if (getUserCount() > 0) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUserList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *游戏开始
     * </pre>
     *
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameStart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.TexasGameStart)
        com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameStartProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameStartProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.class, com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getUserFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        btnSeatId_ = 0;

        sbSeatId_ = 0;

        bbSeatId_ = 0;

        anteAll_ = 0L;

        sbForceBetChip_ = 0L;

        bbForceBetChip_ = 0L;

        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          userBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameStartProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart build() {
        com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart buildPartial() {
        com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart result = new com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.btnSeatId_ = btnSeatId_;
        result.sbSeatId_ = sbSeatId_;
        result.bbSeatId_ = bbSeatId_;
        result.anteAll_ = anteAll_;
        result.sbForceBetChip_ = sbForceBetChip_;
        result.bbForceBetChip_ = bbForceBetChip_;
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart other) {
        if (other == com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart.getDefaultInstance()) return this;
        if (other.getBtnSeatId() != 0) {
          setBtnSeatId(other.getBtnSeatId());
        }
        if (other.getSbSeatId() != 0) {
          setSbSeatId(other.getSbSeatId());
        }
        if (other.getBbSeatId() != 0) {
          setBbSeatId(other.getBbSeatId());
        }
        if (other.getAnteAll() != 0L) {
          setAnteAll(other.getAnteAll());
        }
        if (other.getSbForceBetChip() != 0L) {
          setSbForceBetChip(other.getSbForceBetChip());
        }
        if (other.getBbForceBetChip() != 0L) {
          setBbForceBetChip(other.getBbForceBetChip());
        }
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000040);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int btnSeatId_ ;
      /**
       * <pre>
       *按钮位桌位id
       * </pre>
       *
       * <code>int32 btn_seatId = 1;</code>
       */
      public int getBtnSeatId() {
        return btnSeatId_;
      }
      /**
       * <pre>
       *按钮位桌位id
       * </pre>
       *
       * <code>int32 btn_seatId = 1;</code>
       */
      public Builder setBtnSeatId(int value) {
        
        btnSeatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *按钮位桌位id
       * </pre>
       *
       * <code>int32 btn_seatId = 1;</code>
       */
      public Builder clearBtnSeatId() {
        
        btnSeatId_ = 0;
        onChanged();
        return this;
      }

      private int sbSeatId_ ;
      /**
       * <pre>
       *小盲桌位id
       * </pre>
       *
       * <code>int32 sb_seatId = 2;</code>
       */
      public int getSbSeatId() {
        return sbSeatId_;
      }
      /**
       * <pre>
       *小盲桌位id
       * </pre>
       *
       * <code>int32 sb_seatId = 2;</code>
       */
      public Builder setSbSeatId(int value) {
        
        sbSeatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *小盲桌位id
       * </pre>
       *
       * <code>int32 sb_seatId = 2;</code>
       */
      public Builder clearSbSeatId() {
        
        sbSeatId_ = 0;
        onChanged();
        return this;
      }

      private int bbSeatId_ ;
      /**
       * <pre>
       *大盲桌位id
       * </pre>
       *
       * <code>int32 bb_seatId = 3;</code>
       */
      public int getBbSeatId() {
        return bbSeatId_;
      }
      /**
       * <pre>
       *大盲桌位id
       * </pre>
       *
       * <code>int32 bb_seatId = 3;</code>
       */
      public Builder setBbSeatId(int value) {
        
        bbSeatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *大盲桌位id
       * </pre>
       *
       * <code>int32 bb_seatId = 3;</code>
       */
      public Builder clearBbSeatId() {
        
        bbSeatId_ = 0;
        onChanged();
        return this;
      }

      private long anteAll_ ;
      /**
       * <pre>
       *ante总数
       * </pre>
       *
       * <code>int64 ante_all = 4;</code>
       */
      public long getAnteAll() {
        return anteAll_;
      }
      /**
       * <pre>
       *ante总数
       * </pre>
       *
       * <code>int64 ante_all = 4;</code>
       */
      public Builder setAnteAll(long value) {
        
        anteAll_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *ante总数
       * </pre>
       *
       * <code>int64 ante_all = 4;</code>
       */
      public Builder clearAnteAll() {
        
        anteAll_ = 0L;
        onChanged();
        return this;
      }

      private long sbForceBetChip_ ;
      /**
       * <pre>
       *小盲
       * </pre>
       *
       * <code>int64 sb_force_bet_chip = 5;</code>
       */
      public long getSbForceBetChip() {
        return sbForceBetChip_;
      }
      /**
       * <pre>
       *小盲
       * </pre>
       *
       * <code>int64 sb_force_bet_chip = 5;</code>
       */
      public Builder setSbForceBetChip(long value) {
        
        sbForceBetChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *小盲
       * </pre>
       *
       * <code>int64 sb_force_bet_chip = 5;</code>
       */
      public Builder clearSbForceBetChip() {
        
        sbForceBetChip_ = 0L;
        onChanged();
        return this;
      }

      private long bbForceBetChip_ ;
      /**
       * <pre>
       *大盲
       * </pre>
       *
       * <code>int64 bb_force_bet_chip = 6;</code>
       */
      public long getBbForceBetChip() {
        return bbForceBetChip_;
      }
      /**
       * <pre>
       *大盲
       * </pre>
       *
       * <code>int64 bb_force_bet_chip = 6;</code>
       */
      public Builder setBbForceBetChip(long value) {
        
        bbForceBetChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *大盲
       * </pre>
       *
       * <code>int64 bb_force_bet_chip = 6;</code>
       */
      public Builder clearBbForceBetChip() {
        
        bbForceBetChip_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.poker.protocols.texaspoker.GameUserProto.GameUser> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          user_ = new java.util.ArrayList<com.poker.protocols.texaspoker.GameUserProto.GameUser>(user_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.poker.protocols.texaspoker.GameUserProto.GameUser, com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder, com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder> userBuilder_;

      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public java.util.List<com.poker.protocols.texaspoker.GameUserProto.GameUser> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public com.poker.protocols.texaspoker.GameUserProto.GameUser getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder setUser(
          int index, com.poker.protocols.texaspoker.GameUserProto.GameUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder setUser(
          int index, com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder addUser(com.poker.protocols.texaspoker.GameUserProto.GameUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder addUser(
          int index, com.poker.protocols.texaspoker.GameUserProto.GameUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder addUser(
          com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder addUser(
          int index, com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder addAllUser(
          java.lang.Iterable<? extends com.poker.protocols.texaspoker.GameUserProto.GameUser> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public java.util.List<? extends com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            com.poker.protocols.texaspoker.GameUserProto.GameUser.getDefaultInstance());
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, com.poker.protocols.texaspoker.GameUserProto.GameUser.getDefaultInstance());
      }
      /**
       * <pre>
       *桌子上用户信息   
       * </pre>
       *
       * <code>repeated .com.poker.protocols.texaspoker.proto.GameUser user = 7;</code>
       */
      public java.util.List<com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.poker.protocols.texaspoker.GameUserProto.GameUser, com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder, com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.poker.protocols.texaspoker.GameUserProto.GameUser, com.poker.protocols.texaspoker.GameUserProto.GameUser.Builder, com.poker.protocols.texaspoker.GameUserProto.GameUserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.TexasGameStart)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.TexasGameStart)
    private static final com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart();
    }

    public static com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TexasGameStart>
        PARSER = new com.google.protobuf.AbstractParser<TexasGameStart>() {
      public TexasGameStart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TexasGameStart(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TexasGameStart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TexasGameStart> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameStartProto.TexasGameStart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=src/com/poker/protocols/texaspoker/pro" +
      "to/TexasGameStart.proto\022$com.poker.proto" +
      "cols.texaspoker.proto\0327src/com/poker/pro" +
      "tocols/texaspoker/proto/GameUser.proto\"\320" +
      "\001\n\016TexasGameStart\022\022\n\nbtn_seatId\030\001 \001(\005\022\021\n" +
      "\tsb_seatId\030\002 \001(\005\022\021\n\tbb_seatId\030\003 \001(\005\022\020\n\010a" +
      "nte_all\030\004 \001(\003\022\031\n\021sb_force_bet_chip\030\005 \001(\003" +
      "\022\031\n\021bb_force_bet_chip\030\006 \001(\003\022<\n\004user\030\007 \003(" +
      "\0132..com.poker.protocols.texaspoker.proto" +
      ".GameUserB5\n\036com.poker.protocols.texaspo" +
      "kerB\023TexasGameStartProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.poker.protocols.texaspoker.GameUserProto.getDescriptor(),
        }, assigner);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_TexasGameStart_descriptor,
        new java.lang.String[] { "BtnSeatId", "SbSeatId", "BbSeatId", "AnteAll", "SbForceBetChip", "BbForceBetChip", "User", });
    com.poker.protocols.texaspoker.GameUserProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
