// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/poker/protocols/texaspoker/proto/TexasGameEnd.proto

package com.poker.protocols.texaspoker;

public final class TexasGameEndProto {
  private TexasGameEndProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 seateId = 1;</code>
     */
    int getSeateId();

    /**
     * <code>int32 card_result = 2;</code>
     */
    int getCardResult();

    /**
     * <code>repeated int32 cards = 3;</code>
     */
    java.util.List<java.lang.Integer> getCardsList();
    /**
     * <code>repeated int32 cards = 3;</code>
     */
    int getCardsCount();
    /**
     * <code>repeated int32 cards = 3;</code>
     */
    int getCards(int index);

    /**
     * <pre>
     *最终的金币
     * </pre>
     *
     * <code>int64 chip = 4;</code>
     */
    long getChip();

    /**
     * <pre>
     *赢下Pot中的金币
     * </pre>
     *
     * <code>int64 win_pot_chip = 5;</code>
     */
    long getWinPotChip();

    /**
     * <pre>
     *最终输赢的金币
     * </pre>
     *
     * <code>int64 win_chip = 6;</code>
     */
    long getWinChip();
  }
  /**
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      seateId_ = 0;
      cardResult_ = 0;
      cards_ = java.util.Collections.emptyList();
      chip_ = 0L;
      winPotChip_ = 0L;
      winChip_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              seateId_ = input.readInt32();
              break;
            }
            case 16: {

              cardResult_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                cards_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              cards_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                cards_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                cards_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {

              chip_ = input.readInt64();
              break;
            }
            case 40: {

              winPotChip_ = input.readInt64();
              break;
            }
            case 48: {

              winChip_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_Result_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameEndProto.Result.class, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder.class);
    }

    private int bitField0_;
    public static final int SEATEID_FIELD_NUMBER = 1;
    private int seateId_;
    /**
     * <code>int32 seateId = 1;</code>
     */
    public int getSeateId() {
      return seateId_;
    }

    public static final int CARD_RESULT_FIELD_NUMBER = 2;
    private int cardResult_;
    /**
     * <code>int32 card_result = 2;</code>
     */
    public int getCardResult() {
      return cardResult_;
    }

    public static final int CARDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> cards_;
    /**
     * <code>repeated int32 cards = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getCardsList() {
      return cards_;
    }
    /**
     * <code>repeated int32 cards = 3;</code>
     */
    public int getCardsCount() {
      return cards_.size();
    }
    /**
     * <code>repeated int32 cards = 3;</code>
     */
    public int getCards(int index) {
      return cards_.get(index);
    }
    private int cardsMemoizedSerializedSize = -1;

    public static final int CHIP_FIELD_NUMBER = 4;
    private long chip_;
    /**
     * <pre>
     *最终的金币
     * </pre>
     *
     * <code>int64 chip = 4;</code>
     */
    public long getChip() {
      return chip_;
    }

    public static final int WIN_POT_CHIP_FIELD_NUMBER = 5;
    private long winPotChip_;
    /**
     * <pre>
     *赢下Pot中的金币
     * </pre>
     *
     * <code>int64 win_pot_chip = 5;</code>
     */
    public long getWinPotChip() {
      return winPotChip_;
    }

    public static final int WIN_CHIP_FIELD_NUMBER = 6;
    private long winChip_;
    /**
     * <pre>
     *最终输赢的金币
     * </pre>
     *
     * <code>int64 win_chip = 6;</code>
     */
    public long getWinChip() {
      return winChip_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (seateId_ != 0) {
        output.writeInt32(1, seateId_);
      }
      if (cardResult_ != 0) {
        output.writeInt32(2, cardResult_);
      }
      if (getCardsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(cardsMemoizedSerializedSize);
      }
      for (int i = 0; i < cards_.size(); i++) {
        output.writeInt32NoTag(cards_.get(i));
      }
      if (chip_ != 0L) {
        output.writeInt64(4, chip_);
      }
      if (winPotChip_ != 0L) {
        output.writeInt64(5, winPotChip_);
      }
      if (winChip_ != 0L) {
        output.writeInt64(6, winChip_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (seateId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seateId_);
      }
      if (cardResult_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cardResult_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cards_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(cards_.get(i));
        }
        size += dataSize;
        if (!getCardsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cardsMemoizedSerializedSize = dataSize;
      }
      if (chip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, chip_);
      }
      if (winPotChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, winPotChip_);
      }
      if (winChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, winChip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameEndProto.Result)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameEndProto.Result other = (com.poker.protocols.texaspoker.TexasGameEndProto.Result) obj;

      boolean result = true;
      result = result && (getSeateId()
          == other.getSeateId());
      result = result && (getCardResult()
          == other.getCardResult());
      result = result && getCardsList()
          .equals(other.getCardsList());
      result = result && (getChip()
          == other.getChip());
      result = result && (getWinPotChip()
          == other.getWinPotChip());
      result = result && (getWinChip()
          == other.getWinChip());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEATEID_FIELD_NUMBER;
      hash = (53 * hash) + getSeateId();
      hash = (37 * hash) + CARD_RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getCardResult();
      if (getCardsCount() > 0) {
        hash = (37 * hash) + CARDS_FIELD_NUMBER;
        hash = (53 * hash) + getCardsList().hashCode();
      }
      hash = (37 * hash) + CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getChip());
      hash = (37 * hash) + WIN_POT_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWinPotChip());
      hash = (37 * hash) + WIN_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getWinChip());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(byte[] data,int offset ,int length)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data,offset,length);
        }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
    		byte[] data,int offset ,int length,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data,offset,length, extensionRegistry);
        }
   //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameEndProto.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.Result)
        com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameEndProto.Result.class, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameEndProto.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        seateId_ = 0;

        cardResult_ = 0;

        cards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        chip_ = 0L;

        winPotChip_ = 0L;

        winChip_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_Result_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameEndProto.Result getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.Result.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameEndProto.Result build() {
        com.poker.protocols.texaspoker.TexasGameEndProto.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameEndProto.Result buildPartial() {
        com.poker.protocols.texaspoker.TexasGameEndProto.Result result = new com.poker.protocols.texaspoker.TexasGameEndProto.Result(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.seateId_ = seateId_;
        result.cardResult_ = cardResult_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.cards_ = cards_;
        result.chip_ = chip_;
        result.winPotChip_ = winPotChip_;
        result.winChip_ = winChip_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameEndProto.Result) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameEndProto.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameEndProto.Result other) {
        if (other == com.poker.protocols.texaspoker.TexasGameEndProto.Result.getDefaultInstance()) return this;
        if (other.getSeateId() != 0) {
          setSeateId(other.getSeateId());
        }
        if (other.getCardResult() != 0) {
          setCardResult(other.getCardResult());
        }
        if (!other.cards_.isEmpty()) {
          if (cards_.isEmpty()) {
            cards_ = other.cards_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCardsIsMutable();
            cards_.addAll(other.cards_);
          }
          onChanged();
        }
        if (other.getChip() != 0L) {
          setChip(other.getChip());
        }
        if (other.getWinPotChip() != 0L) {
          setWinPotChip(other.getWinPotChip());
        }
        if (other.getWinChip() != 0L) {
          setWinChip(other.getWinChip());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameEndProto.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameEndProto.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int seateId_ ;
      /**
       * <code>int32 seateId = 1;</code>
       */
      public int getSeateId() {
        return seateId_;
      }
      /**
       * <code>int32 seateId = 1;</code>
       */
      public Builder setSeateId(int value) {
        
        seateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 seateId = 1;</code>
       */
      public Builder clearSeateId() {
        
        seateId_ = 0;
        onChanged();
        return this;
      }

      private int cardResult_ ;
      /**
       * <code>int32 card_result = 2;</code>
       */
      public int getCardResult() {
        return cardResult_;
      }
      /**
       * <code>int32 card_result = 2;</code>
       */
      public Builder setCardResult(int value) {
        
        cardResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 card_result = 2;</code>
       */
      public Builder clearCardResult() {
        
        cardResult_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> cards_ = java.util.Collections.emptyList();
      private void ensureCardsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          cards_ = new java.util.ArrayList<java.lang.Integer>(cards_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getCardsList() {
        return java.util.Collections.unmodifiableList(cards_);
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public int getCardsCount() {
        return cards_.size();
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public int getCards(int index) {
        return cards_.get(index);
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public Builder setCards(
          int index, int value) {
        ensureCardsIsMutable();
        cards_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public Builder addCards(int value) {
        ensureCardsIsMutable();
        cards_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public Builder addAllCards(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCardsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cards_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 3;</code>
       */
      public Builder clearCards() {
        cards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private long chip_ ;
      /**
       * <pre>
       *最终的金币
       * </pre>
       *
       * <code>int64 chip = 4;</code>
       */
      public long getChip() {
        return chip_;
      }
      /**
       * <pre>
       *最终的金币
       * </pre>
       *
       * <code>int64 chip = 4;</code>
       */
      public Builder setChip(long value) {
        
        chip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最终的金币
       * </pre>
       *
       * <code>int64 chip = 4;</code>
       */
      public Builder clearChip() {
        
        chip_ = 0L;
        onChanged();
        return this;
      }

      private long winPotChip_ ;
      /**
       * <pre>
       *赢下Pot中的金币
       * </pre>
       *
       * <code>int64 win_pot_chip = 5;</code>
       */
      public long getWinPotChip() {
        return winPotChip_;
      }
      /**
       * <pre>
       *赢下Pot中的金币
       * </pre>
       *
       * <code>int64 win_pot_chip = 5;</code>
       */
      public Builder setWinPotChip(long value) {
        
        winPotChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *赢下Pot中的金币
       * </pre>
       *
       * <code>int64 win_pot_chip = 5;</code>
       */
      public Builder clearWinPotChip() {
        
        winPotChip_ = 0L;
        onChanged();
        return this;
      }

      private long winChip_ ;
      /**
       * <pre>
       *最终输赢的金币
       * </pre>
       *
       * <code>int64 win_chip = 6;</code>
       */
      public long getWinChip() {
        return winChip_;
      }
      /**
       * <pre>
       *最终输赢的金币
       * </pre>
       *
       * <code>int64 win_chip = 6;</code>
       */
      public Builder setWinChip(long value) {
        
        winChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *最终输赢的金币
       * </pre>
       *
       * <code>int64 win_chip = 6;</code>
       */
      public Builder clearWinChip() {
        
        winChip_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.Result)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.Result)
    private static final com.poker.protocols.texaspoker.TexasGameEndProto.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameEndProto.Result();
    }

    public static com.poker.protocols.texaspoker.TexasGameEndProto.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameEndProto.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TexasGameEndOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.TexasGameEnd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    java.util.List<com.poker.protocols.texaspoker.TexasGameEndProto.Result> 
        getMResultsList();
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    com.poker.protocols.texaspoker.TexasGameEndProto.Result getMResults(int index);
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    int getMResultsCount();
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    java.util.List<? extends com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder> 
        getMResultsOrBuilderList();
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder getMResultsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameEnd}
   */
  public  static final class TexasGameEnd extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.TexasGameEnd)
      TexasGameEndOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TexasGameEnd.newBuilder() to construct.
    private TexasGameEnd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TexasGameEnd() {
      mResults_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TexasGameEnd(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                mResults_ = new java.util.ArrayList<com.poker.protocols.texaspoker.TexasGameEndProto.Result>();
                mutable_bitField0_ |= 0x00000001;
              }
              mResults_.add(
                  input.readMessage(com.poker.protocols.texaspoker.TexasGameEndProto.Result.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          mResults_ = java.util.Collections.unmodifiableList(mResults_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.class, com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.Builder.class);
    }

    public static final int MRESULTS_FIELD_NUMBER = 1;
    private java.util.List<com.poker.protocols.texaspoker.TexasGameEndProto.Result> mResults_;
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    public java.util.List<com.poker.protocols.texaspoker.TexasGameEndProto.Result> getMResultsList() {
      return mResults_;
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    public java.util.List<? extends com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder> 
        getMResultsOrBuilderList() {
      return mResults_;
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    public int getMResultsCount() {
      return mResults_.size();
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    public com.poker.protocols.texaspoker.TexasGameEndProto.Result getMResults(int index) {
      return mResults_.get(index);
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
     */
    public com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder getMResultsOrBuilder(
        int index) {
      return mResults_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < mResults_.size(); i++) {
        output.writeMessage(1, mResults_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < mResults_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mResults_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd other = (com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd) obj;

      boolean result = true;
      result = result && getMResultsList()
          .equals(other.getMResultsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMResultsCount() > 0) {
        hash = (37 * hash) + MRESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getMResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameEnd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.TexasGameEnd)
        com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEndOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.class, com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMResultsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (mResultsBuilder_ == null) {
          mResults_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mResultsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd build() {
        com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd buildPartial() {
        com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd result = new com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd(this);
        int from_bitField0_ = bitField0_;
        if (mResultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            mResults_ = java.util.Collections.unmodifiableList(mResults_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mResults_ = mResults_;
        } else {
          result.mResults_ = mResultsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd other) {
        if (other == com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd.getDefaultInstance()) return this;
        if (mResultsBuilder_ == null) {
          if (!other.mResults_.isEmpty()) {
            if (mResults_.isEmpty()) {
              mResults_ = other.mResults_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMResultsIsMutable();
              mResults_.addAll(other.mResults_);
            }
            onChanged();
          }
        } else {
          if (!other.mResults_.isEmpty()) {
            if (mResultsBuilder_.isEmpty()) {
              mResultsBuilder_.dispose();
              mResultsBuilder_ = null;
              mResults_ = other.mResults_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mResultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMResultsFieldBuilder() : null;
            } else {
              mResultsBuilder_.addAllMessages(other.mResults_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.poker.protocols.texaspoker.TexasGameEndProto.Result> mResults_ =
        java.util.Collections.emptyList();
      private void ensureMResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          mResults_ = new java.util.ArrayList<com.poker.protocols.texaspoker.TexasGameEndProto.Result>(mResults_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.poker.protocols.texaspoker.TexasGameEndProto.Result, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder, com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder> mResultsBuilder_;

      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public java.util.List<com.poker.protocols.texaspoker.TexasGameEndProto.Result> getMResultsList() {
        if (mResultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mResults_);
        } else {
          return mResultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public int getMResultsCount() {
        if (mResultsBuilder_ == null) {
          return mResults_.size();
        } else {
          return mResultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameEndProto.Result getMResults(int index) {
        if (mResultsBuilder_ == null) {
          return mResults_.get(index);
        } else {
          return mResultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder setMResults(
          int index, com.poker.protocols.texaspoker.TexasGameEndProto.Result value) {
        if (mResultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMResultsIsMutable();
          mResults_.set(index, value);
          onChanged();
        } else {
          mResultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder setMResults(
          int index, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder builderForValue) {
        if (mResultsBuilder_ == null) {
          ensureMResultsIsMutable();
          mResults_.set(index, builderForValue.build());
          onChanged();
        } else {
          mResultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder addMResults(com.poker.protocols.texaspoker.TexasGameEndProto.Result value) {
        if (mResultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMResultsIsMutable();
          mResults_.add(value);
          onChanged();
        } else {
          mResultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder addMResults(
          int index, com.poker.protocols.texaspoker.TexasGameEndProto.Result value) {
        if (mResultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMResultsIsMutable();
          mResults_.add(index, value);
          onChanged();
        } else {
          mResultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder addMResults(
          com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder builderForValue) {
        if (mResultsBuilder_ == null) {
          ensureMResultsIsMutable();
          mResults_.add(builderForValue.build());
          onChanged();
        } else {
          mResultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder addMResults(
          int index, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder builderForValue) {
        if (mResultsBuilder_ == null) {
          ensureMResultsIsMutable();
          mResults_.add(index, builderForValue.build());
          onChanged();
        } else {
          mResultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder addAllMResults(
          java.lang.Iterable<? extends com.poker.protocols.texaspoker.TexasGameEndProto.Result> values) {
        if (mResultsBuilder_ == null) {
          ensureMResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mResults_);
          onChanged();
        } else {
          mResultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder clearMResults() {
        if (mResultsBuilder_ == null) {
          mResults_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mResultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public Builder removeMResults(int index) {
        if (mResultsBuilder_ == null) {
          ensureMResultsIsMutable();
          mResults_.remove(index);
          onChanged();
        } else {
          mResultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder getMResultsBuilder(
          int index) {
        return getMResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder getMResultsOrBuilder(
          int index) {
        if (mResultsBuilder_ == null) {
          return mResults_.get(index);  } else {
          return mResultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public java.util.List<? extends com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder> 
           getMResultsOrBuilderList() {
        if (mResultsBuilder_ != null) {
          return mResultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mResults_);
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder addMResultsBuilder() {
        return getMResultsFieldBuilder().addBuilder(
            com.poker.protocols.texaspoker.TexasGameEndProto.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder addMResultsBuilder(
          int index) {
        return getMResultsFieldBuilder().addBuilder(
            index, com.poker.protocols.texaspoker.TexasGameEndProto.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.Result mResults = 1;</code>
       */
      public java.util.List<com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder> 
           getMResultsBuilderList() {
        return getMResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.poker.protocols.texaspoker.TexasGameEndProto.Result, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder, com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder> 
          getMResultsFieldBuilder() {
        if (mResultsBuilder_ == null) {
          mResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.poker.protocols.texaspoker.TexasGameEndProto.Result, com.poker.protocols.texaspoker.TexasGameEndProto.Result.Builder, com.poker.protocols.texaspoker.TexasGameEndProto.ResultOrBuilder>(
                  mResults_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          mResults_ = null;
        }
        return mResultsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.TexasGameEnd)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.TexasGameEnd)
    private static final com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd();
    }

    public static com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TexasGameEnd>
        PARSER = new com.google.protobuf.AbstractParser<TexasGameEnd>() {
      public TexasGameEnd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TexasGameEnd(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TexasGameEnd> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TexasGameEnd> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameEndProto.TexasGameEnd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_Result_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n;src/com/poker/protocols/texaspoker/pro" +
      "to/TexasGameEnd.proto\022$com.poker.protoco" +
      "ls.texaspoker.proto\"s\n\006Result\022\017\n\007seateId" +
      "\030\001 \001(\005\022\023\n\013card_result\030\002 \001(\005\022\r\n\005cards\030\003 \003" +
      "(\005\022\014\n\004chip\030\004 \001(\003\022\024\n\014win_pot_chip\030\005 \001(\003\022\020" +
      "\n\010win_chip\030\006 \001(\003\"N\n\014TexasGameEnd\022>\n\010mRes" +
      "ults\030\001 \003(\0132,.com.poker.protocols.texaspo" +
      "ker.proto.ResultB3\n\036com.poker.protocols." +
      "texaspokerB\021TexasGameEndProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_poker_protocols_texaspoker_proto_Result_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_poker_protocols_texaspoker_proto_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_Result_descriptor,
        new java.lang.String[] { "SeateId", "CardResult", "Cards", "Chip", "WinPotChip", "WinChip", });
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_TexasGameEnd_descriptor,
        new java.lang.String[] { "MResults", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
