// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/poker/protocols/texaspoker/proto/TexasGameBroadcastPot.proto

package com.poker.protocols.texaspoker;

public final class TexasGameBroadcastPotProto {
  private TexasGameBroadcastPotProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TexasGameBroadcastPotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int64 pots = 1;</code>
     */
    java.util.List<java.lang.Long> getPotsList();
    /**
     * <code>repeated int64 pots = 1;</code>
     */
    int getPotsCount();
    /**
     * <code>repeated int64 pots = 1;</code>
     */
    long getPots(int index);
  }
  /**
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot}
   */
  public  static final class TexasGameBroadcastPot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot)
      TexasGameBroadcastPotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TexasGameBroadcastPot.newBuilder() to construct.
    private TexasGameBroadcastPot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TexasGameBroadcastPot() {
      pots_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TexasGameBroadcastPot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pots_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              pots_.add(input.readInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                pots_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                pots_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pots_ = java.util.Collections.unmodifiableList(pots_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.class, com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.Builder.class);
    }

    public static final int POTS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> pots_;
    /**
     * <code>repeated int64 pots = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getPotsList() {
      return pots_;
    }
    /**
     * <code>repeated int64 pots = 1;</code>
     */
    public int getPotsCount() {
      return pots_.size();
    }
    /**
     * <code>repeated int64 pots = 1;</code>
     */
    public long getPots(int index) {
      return pots_.get(index);
    }
    private int potsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getPotsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(potsMemoizedSerializedSize);
      }
      for (int i = 0; i < pots_.size(); i++) {
        output.writeInt64NoTag(pots_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < pots_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(pots_.get(i));
        }
        size += dataSize;
        if (!getPotsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        potsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot other = (com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot) obj;

      boolean result = true;
      result = result && getPotsList()
          .equals(other.getPotsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPotsCount() > 0) {
        hash = (37 * hash) + POTS_FIELD_NUMBER;
        hash = (53 * hash) + getPotsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot)
        com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.class, com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot build() {
        com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot buildPartial() {
        com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot result = new com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          pots_ = java.util.Collections.unmodifiableList(pots_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.pots_ = pots_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot other) {
        if (other == com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot.getDefaultInstance()) return this;
        if (!other.pots_.isEmpty()) {
          if (pots_.isEmpty()) {
            pots_ = other.pots_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePotsIsMutable();
            pots_.addAll(other.pots_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> pots_ = java.util.Collections.emptyList();
      private void ensurePotsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pots_ = new java.util.ArrayList<java.lang.Long>(pots_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getPotsList() {
        return java.util.Collections.unmodifiableList(pots_);
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public int getPotsCount() {
        return pots_.size();
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public long getPots(int index) {
        return pots_.get(index);
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public Builder setPots(
          int index, long value) {
        ensurePotsIsMutable();
        pots_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public Builder addPots(long value) {
        ensurePotsIsMutable();
        pots_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public Builder addAllPots(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensurePotsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, pots_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 pots = 1;</code>
       */
      public Builder clearPots() {
        pots_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.TexasGameBroadcastPot)
    private static final com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot();
    }

    public static com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TexasGameBroadcastPot>
        PARSER = new com.google.protobuf.AbstractParser<TexasGameBroadcastPot>() {
      public TexasGameBroadcastPot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TexasGameBroadcastPot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TexasGameBroadcastPot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TexasGameBroadcastPot> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameBroadcastPotProto.TexasGameBroadcastPot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nDsrc/com/poker/protocols/texaspoker/pro" +
      "to/TexasGameBroadcastPot.proto\022$com.poke" +
      "r.protocols.texaspoker.proto\"%\n\025TexasGam" +
      "eBroadcastPot\022\014\n\004pots\030\001 \003(\003B<\n\036com.poker" +
      ".protocols.texaspokerB\032TexasGameBroadcas" +
      "tPotProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastPot_descriptor,
        new java.lang.String[] { "Pots", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
