// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/poker/protocols/texaspoker/proto/TexasGameDeal.proto

package com.poker.protocols.texaspoker;

public final class TexasGameDealProto {
  private TexasGameDealProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserCardOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.UserCard)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <code>repeated int32 cards = 2;</code>
     */
    java.util.List<java.lang.Integer> getCardsList();
    /**
     * <code>repeated int32 cards = 2;</code>
     */
    int getCardsCount();
    /**
     * <code>repeated int32 cards = 2;</code>
     */
    int getCards(int index);
  }
  /**
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.UserCard}
   */
  public  static final class UserCard extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.UserCard)
      UserCardOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserCard.newBuilder() to construct.
    private UserCard(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserCard() {
      uid_ = 0L;
      cards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                cards_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              cards_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                cards_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                cards_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_UserCard_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_UserCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.class, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder.class);
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int CARDS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> cards_;
    /**
     * <code>repeated int32 cards = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getCardsList() {
      return cards_;
    }
    /**
     * <code>repeated int32 cards = 2;</code>
     */
    public int getCardsCount() {
      return cards_.size();
    }
    /**
     * <code>repeated int32 cards = 2;</code>
     */
    public int getCards(int index) {
      return cards_.get(index);
    }
    private int cardsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (getCardsList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(cardsMemoizedSerializedSize);
      }
      for (int i = 0; i < cards_.size(); i++) {
        output.writeInt32NoTag(cards_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cards_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(cards_.get(i));
        }
        size += dataSize;
        if (!getCardsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        cardsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameDealProto.UserCard)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameDealProto.UserCard other = (com.poker.protocols.texaspoker.TexasGameDealProto.UserCard) obj;

      boolean result = true;
      result = result && (getUid()
          == other.getUid());
      result = result && getCardsList()
          .equals(other.getCardsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      if (getCardsCount() > 0) {
        hash = (37 * hash) + CARDS_FIELD_NUMBER;
        hash = (53 * hash) + getCardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(byte[] data,int offset ,int length)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data,offset,length);
        }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
    		byte[] data,int offset ,int length,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data,offset,length, extensionRegistry);
        }
   //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameDealProto.UserCard prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.UserCard}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.UserCard)
        com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_UserCard_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_UserCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.class, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        cards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_UserCard_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard build() {
        com.poker.protocols.texaspoker.TexasGameDealProto.UserCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard buildPartial() {
        com.poker.protocols.texaspoker.TexasGameDealProto.UserCard result = new com.poker.protocols.texaspoker.TexasGameDealProto.UserCard(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.uid_ = uid_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          cards_ = java.util.Collections.unmodifiableList(cards_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.cards_ = cards_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameDealProto.UserCard) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameDealProto.UserCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameDealProto.UserCard other) {
        if (other == com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.cards_.isEmpty()) {
          if (cards_.isEmpty()) {
            cards_ = other.cards_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCardsIsMutable();
            cards_.addAll(other.cards_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameDealProto.UserCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameDealProto.UserCard) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> cards_ = java.util.Collections.emptyList();
      private void ensureCardsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          cards_ = new java.util.ArrayList<java.lang.Integer>(cards_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getCardsList() {
        return java.util.Collections.unmodifiableList(cards_);
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public int getCardsCount() {
        return cards_.size();
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public int getCards(int index) {
        return cards_.get(index);
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public Builder setCards(
          int index, int value) {
        ensureCardsIsMutable();
        cards_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public Builder addCards(int value) {
        ensureCardsIsMutable();
        cards_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public Builder addAllCards(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCardsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cards_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 cards = 2;</code>
       */
      public Builder clearCards() {
        cards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.UserCard)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.UserCard)
    private static final com.poker.protocols.texaspoker.TexasGameDealProto.UserCard DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameDealProto.UserCard();
    }

    public static com.poker.protocols.texaspoker.TexasGameDealProto.UserCard getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserCard>
        PARSER = new com.google.protobuf.AbstractParser<UserCard>() {
      public UserCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserCard(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserCard> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserCard> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TexasGameDealOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.TexasGameDeal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *小盲uid
     * </pre>
     *
     * <code>int32 sb_uid = 1;</code>
     */
    int getSbUid();

    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    java.util.List<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard> 
        getMUserCardsList();
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    com.poker.protocols.texaspoker.TexasGameDealProto.UserCard getMUserCards(int index);
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    int getMUserCardsCount();
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    java.util.List<? extends com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder> 
        getMUserCardsOrBuilderList();
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder getMUserCardsOrBuilder(
        int index);
  }
  /**
   * <pre>
   *游戏发牌
   * </pre>
   *
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameDeal}
   */
  public  static final class TexasGameDeal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.TexasGameDeal)
      TexasGameDealOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TexasGameDeal.newBuilder() to construct.
    private TexasGameDeal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TexasGameDeal() {
      sbUid_ = 0;
      mUserCards_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TexasGameDeal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sbUid_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                mUserCards_ = new java.util.ArrayList<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard>();
                mutable_bitField0_ |= 0x00000002;
              }
              mUserCards_.add(
                  input.readMessage(com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          mUserCards_ = java.util.Collections.unmodifiableList(mUserCards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.class, com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.Builder.class);
    }

    private int bitField0_;
    public static final int SB_UID_FIELD_NUMBER = 1;
    private int sbUid_;
    /**
     * <pre>
     *小盲uid
     * </pre>
     *
     * <code>int32 sb_uid = 1;</code>
     */
    public int getSbUid() {
      return sbUid_;
    }

    public static final int MUSERCARDS_FIELD_NUMBER = 2;
    private java.util.List<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard> mUserCards_;
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    public java.util.List<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard> getMUserCardsList() {
      return mUserCards_;
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    public java.util.List<? extends com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder> 
        getMUserCardsOrBuilderList() {
      return mUserCards_;
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    public int getMUserCardsCount() {
      return mUserCards_.size();
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard getMUserCards(int index) {
      return mUserCards_.get(index);
    }
    /**
     * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
     */
    public com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder getMUserCardsOrBuilder(
        int index) {
      return mUserCards_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sbUid_ != 0) {
        output.writeInt32(1, sbUid_);
      }
      for (int i = 0; i < mUserCards_.size(); i++) {
        output.writeMessage(2, mUserCards_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sbUid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sbUid_);
      }
      for (int i = 0; i < mUserCards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, mUserCards_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal other = (com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal) obj;

      boolean result = true;
      result = result && (getSbUid()
          == other.getSbUid());
      result = result && getMUserCardsList()
          .equals(other.getMUserCardsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SB_UID_FIELD_NUMBER;
      hash = (53 * hash) + getSbUid();
      if (getMUserCardsCount() > 0) {
        hash = (37 * hash) + MUSERCARDS_FIELD_NUMBER;
        hash = (53 * hash) + getMUserCardsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(byte[] data,int offset ,int length)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data,offset,length);
        }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
    		byte[] data,int offset ,int length,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data,offset,length, extensionRegistry);
        }
   //-----------------------------------------------------
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *游戏发牌
     * </pre>
     *
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameDeal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.TexasGameDeal)
        com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDealOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.class, com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMUserCardsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        sbUid_ = 0;

        if (mUserCardsBuilder_ == null) {
          mUserCards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          mUserCardsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal build() {
        com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal buildPartial() {
        com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal result = new com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.sbUid_ = sbUid_;
        if (mUserCardsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            mUserCards_ = java.util.Collections.unmodifiableList(mUserCards_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.mUserCards_ = mUserCards_;
        } else {
          result.mUserCards_ = mUserCardsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal other) {
        if (other == com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal.getDefaultInstance()) return this;
        if (other.getSbUid() != 0) {
          setSbUid(other.getSbUid());
        }
        if (mUserCardsBuilder_ == null) {
          if (!other.mUserCards_.isEmpty()) {
            if (mUserCards_.isEmpty()) {
              mUserCards_ = other.mUserCards_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMUserCardsIsMutable();
              mUserCards_.addAll(other.mUserCards_);
            }
            onChanged();
          }
        } else {
          if (!other.mUserCards_.isEmpty()) {
            if (mUserCardsBuilder_.isEmpty()) {
              mUserCardsBuilder_.dispose();
              mUserCardsBuilder_ = null;
              mUserCards_ = other.mUserCards_;
              bitField0_ = (bitField0_ & ~0x00000002);
              mUserCardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMUserCardsFieldBuilder() : null;
            } else {
              mUserCardsBuilder_.addAllMessages(other.mUserCards_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sbUid_ ;
      /**
       * <pre>
       *小盲uid
       * </pre>
       *
       * <code>int32 sb_uid = 1;</code>
       */
      public int getSbUid() {
        return sbUid_;
      }
      /**
       * <pre>
       *小盲uid
       * </pre>
       *
       * <code>int32 sb_uid = 1;</code>
       */
      public Builder setSbUid(int value) {
        
        sbUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *小盲uid
       * </pre>
       *
       * <code>int32 sb_uid = 1;</code>
       */
      public Builder clearSbUid() {
        
        sbUid_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard> mUserCards_ =
        java.util.Collections.emptyList();
      private void ensureMUserCardsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          mUserCards_ = new java.util.ArrayList<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard>(mUserCards_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.poker.protocols.texaspoker.TexasGameDealProto.UserCard, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder, com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder> mUserCardsBuilder_;

      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public java.util.List<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard> getMUserCardsList() {
        if (mUserCardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mUserCards_);
        } else {
          return mUserCardsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public int getMUserCardsCount() {
        if (mUserCardsBuilder_ == null) {
          return mUserCards_.size();
        } else {
          return mUserCardsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard getMUserCards(int index) {
        if (mUserCardsBuilder_ == null) {
          return mUserCards_.get(index);
        } else {
          return mUserCardsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder setMUserCards(
          int index, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard value) {
        if (mUserCardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMUserCardsIsMutable();
          mUserCards_.set(index, value);
          onChanged();
        } else {
          mUserCardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder setMUserCards(
          int index, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder builderForValue) {
        if (mUserCardsBuilder_ == null) {
          ensureMUserCardsIsMutable();
          mUserCards_.set(index, builderForValue.build());
          onChanged();
        } else {
          mUserCardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder addMUserCards(com.poker.protocols.texaspoker.TexasGameDealProto.UserCard value) {
        if (mUserCardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMUserCardsIsMutable();
          mUserCards_.add(value);
          onChanged();
        } else {
          mUserCardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder addMUserCards(
          int index, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard value) {
        if (mUserCardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMUserCardsIsMutable();
          mUserCards_.add(index, value);
          onChanged();
        } else {
          mUserCardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder addMUserCards(
          com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder builderForValue) {
        if (mUserCardsBuilder_ == null) {
          ensureMUserCardsIsMutable();
          mUserCards_.add(builderForValue.build());
          onChanged();
        } else {
          mUserCardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder addMUserCards(
          int index, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder builderForValue) {
        if (mUserCardsBuilder_ == null) {
          ensureMUserCardsIsMutable();
          mUserCards_.add(index, builderForValue.build());
          onChanged();
        } else {
          mUserCardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder addAllMUserCards(
          java.lang.Iterable<? extends com.poker.protocols.texaspoker.TexasGameDealProto.UserCard> values) {
        if (mUserCardsBuilder_ == null) {
          ensureMUserCardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, mUserCards_);
          onChanged();
        } else {
          mUserCardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder clearMUserCards() {
        if (mUserCardsBuilder_ == null) {
          mUserCards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          mUserCardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public Builder removeMUserCards(int index) {
        if (mUserCardsBuilder_ == null) {
          ensureMUserCardsIsMutable();
          mUserCards_.remove(index);
          onChanged();
        } else {
          mUserCardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder getMUserCardsBuilder(
          int index) {
        return getMUserCardsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder getMUserCardsOrBuilder(
          int index) {
        if (mUserCardsBuilder_ == null) {
          return mUserCards_.get(index);  } else {
          return mUserCardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public java.util.List<? extends com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder> 
           getMUserCardsOrBuilderList() {
        if (mUserCardsBuilder_ != null) {
          return mUserCardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mUserCards_);
        }
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder addMUserCardsBuilder() {
        return getMUserCardsFieldBuilder().addBuilder(
            com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.getDefaultInstance());
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder addMUserCardsBuilder(
          int index) {
        return getMUserCardsFieldBuilder().addBuilder(
            index, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.getDefaultInstance());
      }
      /**
       * <code>repeated .com.poker.protocols.texaspoker.proto.UserCard mUserCards = 2;</code>
       */
      public java.util.List<com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder> 
           getMUserCardsBuilderList() {
        return getMUserCardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.poker.protocols.texaspoker.TexasGameDealProto.UserCard, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder, com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder> 
          getMUserCardsFieldBuilder() {
        if (mUserCardsBuilder_ == null) {
          mUserCardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.poker.protocols.texaspoker.TexasGameDealProto.UserCard, com.poker.protocols.texaspoker.TexasGameDealProto.UserCard.Builder, com.poker.protocols.texaspoker.TexasGameDealProto.UserCardOrBuilder>(
                  mUserCards_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          mUserCards_ = null;
        }
        return mUserCardsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.TexasGameDeal)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.TexasGameDeal)
    private static final com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal();
    }

    public static com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TexasGameDeal>
        PARSER = new com.google.protobuf.AbstractParser<TexasGameDeal>() {
      public TexasGameDeal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TexasGameDeal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TexasGameDeal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TexasGameDeal> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameDealProto.TexasGameDeal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_UserCard_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_UserCard_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<src/com/poker/protocols/texaspoker/pro" +
      "to/TexasGameDeal.proto\022$com.poker.protoc" +
      "ols.texaspoker.proto\"&\n\010UserCard\022\013\n\003uid\030" +
      "\001 \001(\003\022\r\n\005cards\030\002 \003(\005\"c\n\rTexasGameDeal\022\016\n" +
      "\006sb_uid\030\001 \001(\005\022B\n\nmUserCards\030\002 \003(\0132..com." +
      "poker.protocols.texaspoker.proto.UserCar" +
      "dB4\n\036com.poker.protocols.texaspokerB\022Tex" +
      "asGameDealProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_poker_protocols_texaspoker_proto_UserCard_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_poker_protocols_texaspoker_proto_UserCard_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_UserCard_descriptor,
        new java.lang.String[] { "Uid", "Cards", });
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_TexasGameDeal_descriptor,
        new java.lang.String[] { "SbUid", "MUserCards", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
