// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/com/poker/protocols/texaspoker/proto/TexasGameBroadcastNextOperate.proto

package com.poker.protocols.texaspoker;

public final class TexasGameBroadcastNextOperateProto {
  private TexasGameBroadcastNextOperateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TexasGameBroadcastNextOperateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 next_op_seatId = 1;</code>
     */
    int getNextOpSeatId();

    /**
     * <code>int64 next_op_call_chip = 2;</code>
     */
    long getNextOpCallChip();

    /**
     * <code>int64 next_op_min_raise_chip = 3;</code>
     */
    long getNextOpMinRaiseChip();

    /**
     * <code>int64 next_op_max_raise_chip = 4;</code>
     */
    long getNextOpMaxRaiseChip();
  }
  /**
   * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate}
   */
  public  static final class TexasGameBroadcastNextOperate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate)
      TexasGameBroadcastNextOperateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TexasGameBroadcastNextOperate.newBuilder() to construct.
    private TexasGameBroadcastNextOperate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TexasGameBroadcastNextOperate() {
      nextOpSeatId_ = 0;
      nextOpCallChip_ = 0L;
      nextOpMinRaiseChip_ = 0L;
      nextOpMaxRaiseChip_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TexasGameBroadcastNextOperate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              nextOpSeatId_ = input.readInt32();
              break;
            }
            case 16: {

              nextOpCallChip_ = input.readInt64();
              break;
            }
            case 24: {

              nextOpMinRaiseChip_ = input.readInt64();
              break;
            }
            case 32: {

              nextOpMaxRaiseChip_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.class, com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.Builder.class);
    }

    public static final int NEXT_OP_SEATID_FIELD_NUMBER = 1;
    private int nextOpSeatId_;
    /**
     * <code>int32 next_op_seatId = 1;</code>
     */
    public int getNextOpSeatId() {
      return nextOpSeatId_;
    }

    public static final int NEXT_OP_CALL_CHIP_FIELD_NUMBER = 2;
    private long nextOpCallChip_;
    /**
     * <code>int64 next_op_call_chip = 2;</code>
     */
    public long getNextOpCallChip() {
      return nextOpCallChip_;
    }

    public static final int NEXT_OP_MIN_RAISE_CHIP_FIELD_NUMBER = 3;
    private long nextOpMinRaiseChip_;
    /**
     * <code>int64 next_op_min_raise_chip = 3;</code>
     */
    public long getNextOpMinRaiseChip() {
      return nextOpMinRaiseChip_;
    }

    public static final int NEXT_OP_MAX_RAISE_CHIP_FIELD_NUMBER = 4;
    private long nextOpMaxRaiseChip_;
    /**
     * <code>int64 next_op_max_raise_chip = 4;</code>
     */
    public long getNextOpMaxRaiseChip() {
      return nextOpMaxRaiseChip_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (nextOpSeatId_ != 0) {
        output.writeInt32(1, nextOpSeatId_);
      }
      if (nextOpCallChip_ != 0L) {
        output.writeInt64(2, nextOpCallChip_);
      }
      if (nextOpMinRaiseChip_ != 0L) {
        output.writeInt64(3, nextOpMinRaiseChip_);
      }
      if (nextOpMaxRaiseChip_ != 0L) {
        output.writeInt64(4, nextOpMaxRaiseChip_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nextOpSeatId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nextOpSeatId_);
      }
      if (nextOpCallChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nextOpCallChip_);
      }
      if (nextOpMinRaiseChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, nextOpMinRaiseChip_);
      }
      if (nextOpMaxRaiseChip_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, nextOpMaxRaiseChip_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate)) {
        return super.equals(obj);
      }
      com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate other = (com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate) obj;

      boolean result = true;
      result = result && (getNextOpSeatId()
          == other.getNextOpSeatId());
      result = result && (getNextOpCallChip()
          == other.getNextOpCallChip());
      result = result && (getNextOpMinRaiseChip()
          == other.getNextOpMinRaiseChip());
      result = result && (getNextOpMaxRaiseChip()
          == other.getNextOpMaxRaiseChip());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NEXT_OP_SEATID_FIELD_NUMBER;
      hash = (53 * hash) + getNextOpSeatId();
      hash = (37 * hash) + NEXT_OP_CALL_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNextOpCallChip());
      hash = (37 * hash) + NEXT_OP_MIN_RAISE_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNextOpMinRaiseChip());
      hash = (37 * hash) + NEXT_OP_MAX_RAISE_CHIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNextOpMaxRaiseChip());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate)
        com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.class, com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.Builder.class);
      }

      // Construct using com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nextOpSeatId_ = 0;

        nextOpCallChip_ = 0L;

        nextOpMinRaiseChip_ = 0L;

        nextOpMaxRaiseChip_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_descriptor;
      }

      public com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate getDefaultInstanceForType() {
        return com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.getDefaultInstance();
      }

      public com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate build() {
        com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate buildPartial() {
        com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate result = new com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate(this);
        result.nextOpSeatId_ = nextOpSeatId_;
        result.nextOpCallChip_ = nextOpCallChip_;
        result.nextOpMinRaiseChip_ = nextOpMinRaiseChip_;
        result.nextOpMaxRaiseChip_ = nextOpMaxRaiseChip_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate) {
          return mergeFrom((com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate other) {
        if (other == com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate.getDefaultInstance()) return this;
        if (other.getNextOpSeatId() != 0) {
          setNextOpSeatId(other.getNextOpSeatId());
        }
        if (other.getNextOpCallChip() != 0L) {
          setNextOpCallChip(other.getNextOpCallChip());
        }
        if (other.getNextOpMinRaiseChip() != 0L) {
          setNextOpMinRaiseChip(other.getNextOpMinRaiseChip());
        }
        if (other.getNextOpMaxRaiseChip() != 0L) {
          setNextOpMaxRaiseChip(other.getNextOpMaxRaiseChip());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int nextOpSeatId_ ;
      /**
       * <code>int32 next_op_seatId = 1;</code>
       */
      public int getNextOpSeatId() {
        return nextOpSeatId_;
      }
      /**
       * <code>int32 next_op_seatId = 1;</code>
       */
      public Builder setNextOpSeatId(int value) {
        
        nextOpSeatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 next_op_seatId = 1;</code>
       */
      public Builder clearNextOpSeatId() {
        
        nextOpSeatId_ = 0;
        onChanged();
        return this;
      }

      private long nextOpCallChip_ ;
      /**
       * <code>int64 next_op_call_chip = 2;</code>
       */
      public long getNextOpCallChip() {
        return nextOpCallChip_;
      }
      /**
       * <code>int64 next_op_call_chip = 2;</code>
       */
      public Builder setNextOpCallChip(long value) {
        
        nextOpCallChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 next_op_call_chip = 2;</code>
       */
      public Builder clearNextOpCallChip() {
        
        nextOpCallChip_ = 0L;
        onChanged();
        return this;
      }

      private long nextOpMinRaiseChip_ ;
      /**
       * <code>int64 next_op_min_raise_chip = 3;</code>
       */
      public long getNextOpMinRaiseChip() {
        return nextOpMinRaiseChip_;
      }
      /**
       * <code>int64 next_op_min_raise_chip = 3;</code>
       */
      public Builder setNextOpMinRaiseChip(long value) {
        
        nextOpMinRaiseChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 next_op_min_raise_chip = 3;</code>
       */
      public Builder clearNextOpMinRaiseChip() {
        
        nextOpMinRaiseChip_ = 0L;
        onChanged();
        return this;
      }

      private long nextOpMaxRaiseChip_ ;
      /**
       * <code>int64 next_op_max_raise_chip = 4;</code>
       */
      public long getNextOpMaxRaiseChip() {
        return nextOpMaxRaiseChip_;
      }
      /**
       * <code>int64 next_op_max_raise_chip = 4;</code>
       */
      public Builder setNextOpMaxRaiseChip(long value) {
        
        nextOpMaxRaiseChip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 next_op_max_raise_chip = 4;</code>
       */
      public Builder clearNextOpMaxRaiseChip() {
        
        nextOpMaxRaiseChip_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate)
    }

    // @@protoc_insertion_point(class_scope:com.poker.protocols.texaspoker.proto.TexasGameBroadcastNextOperate)
    private static final com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate();
    }

    public static com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TexasGameBroadcastNextOperate>
        PARSER = new com.google.protobuf.AbstractParser<TexasGameBroadcastNextOperate>() {
      public TexasGameBroadcastNextOperate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TexasGameBroadcastNextOperate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TexasGameBroadcastNextOperate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TexasGameBroadcastNextOperate> getParserForType() {
      return PARSER;
    }

    public com.poker.protocols.texaspoker.TexasGameBroadcastNextOperateProto.TexasGameBroadcastNextOperate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nLsrc/com/poker/protocols/texaspoker/pro" +
      "to/TexasGameBroadcastNextOperate.proto\022$" +
      "com.poker.protocols.texaspoker.proto\"\222\001\n" +
      "\035TexasGameBroadcastNextOperate\022\026\n\016next_o" +
      "p_seatId\030\001 \001(\005\022\031\n\021next_op_call_chip\030\002 \001(" +
      "\003\022\036\n\026next_op_min_raise_chip\030\003 \001(\003\022\036\n\026nex" +
      "t_op_max_raise_chip\030\004 \001(\003BD\n\036com.poker.p" +
      "rotocols.texaspokerB\"TexasGameBroadcastN" +
      "extOperateProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_poker_protocols_texaspoker_proto_TexasGameBroadcastNextOperate_descriptor,
        new java.lang.String[] { "NextOpSeatId", "NextOpCallChip", "NextOpMinRaiseChip", "NextOpMaxRaiseChip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
